version: "3.9"

networks:
  my-net:
    driver: bridge

services:
  fastapi_service:
    build:
      context: .
      dockerfile: Dockerfile
    hostname: fastapi_service
    container_name: fastapi_service
    depends_on:
      - db_postgres
    ports:
      - "9110:9110"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - DB_HOST=db_postgres
      - DB_PORT=5432
      - TARGET_AUTH_HOST=localhost
      - TARGET_AUTH_PORT=9110
    volumes:
      - ./:/home/app
    networks:
      - my-net

  db_postgres:
    image: postgres:14.3-alpine
    hostname: db_postgres
    container_name: db_postgres
    restart: on-failure
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - "5432:5432"
    security_opt: # Add security options
      - "no-new-privileges:true"
    read_only: true  # Add the read_only option to make the root filesystem read-only
    #    volumes:
#      - db-postgres:/var/lib/postgresql/data
    networks:
      - my-net

  redis_service: # Define the Redis service
    image: redis:latest
    hostname: redis_service
    container_name: redis_service
    ports:
      - "6379:6379"  # Expose Redis default port
    networks:
      - my-net

#volumes:
#  db-postgres:
#    driver: local
