apiVersion: apps/v1
kind: Deployment
metadata:
  name: easy-auth
spec:
  replicas: 1
  selector:
    matchLabels:
      app: easy-auth
  template:
    metadata:
      labels:
        app: easy-auth
    spec:
      containers:
        - name: easy-auth
          image: yaknafo/easy-auth:1.03
          env:
          - name: POSTGRES_USER
            valueFrom:
              secretKeyRef:
                name: easy-auth-secret
                key: POSTGRES_USER
          - name: POSTGRES_PASSWORD
            valueFrom:
              secretKeyRef:
                name: easy-auth-secret
                key: POSTGRES_PASSWORD
          - name: DB_HOST
            value: postgres-service
          - name: DB_PORT
            valueFrom:
              secretKeyRef:
                name: easy-auth-secret
                key: DB_PORT
          - name: tyk_port
            value: "8080"
          - name: tyk_host
            value: tyk-svc

          ports:
            - containerPort: 9110