apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: easy-auth-ingress
  annotations:
#    kubernetes.io/ingress.class:tyk
    nginx.ingress.kubernetes.io/rewrite-target: /api/auth
spec:
  rules:
    - host: login-local-easy-auth.com
      http:
        paths:
          - path: /api/auth
            pathType: Prefix
            backend:
              service:
                name: easy-auth-service
                port:
                  number: 9110